---
title: "visualizations"
author: "Iris Kern"
date: "2023-08-09"
output: html_document
---

```{r}
colors <- c("C" = "plum2", "LH" = "lightcoral", "LL" = "gold", "RH" = "brown3", "RL" = "orange", "T0" = "grey50", 
                              "ZF" = "mediumpurple", "ZH" = "lightseagreen", "ZL" = "darkslategray2")
```

```{r}
metadata_targ %>% 
  mutate(replicate_num = str_extract(replicate, "\\d$")) %>% 
  group_by(treatment, date) %>% 
  mutate(pc_avg = mean(pc_um)) %>% 
  mutate(pn_avg = mean(pn_um)) %>% 
  distinct(pc_avg, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = pc_avg, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()
```


# timeseries of trimethylamine n-oxide
```{r}
isologs_quant %>% 
  filter(metabolite == "Trimethylamine N-oxide") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "Trimethylamine N-oxide") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```


# L-Alanine
```{r}
isologs_quant %>% 
  filter(metabolite == "L-Alanine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "L-Alanine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

# Cytosine
```{r}
isologs_quant %>% 
  filter(metabolite == "Cytosine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "Cytosine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```
           "L-Proline"              "Glycine betaine"       
 [6] "L-Valine"               "L-Isoleucine"           "Homarine"               "L-Methionine"           "Guanine"               
[11] "L-Histidine"            "L-Arginine"             "Arsenobetaine"         

# L-Proline
```{r}
isologs_quant %>% 
  filter(metabolite == "L-Proline") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "L-Proline") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

# Glycine Betaine
```{r}
isologs_quant %>% 
  filter(metabolite == "Glycine betaine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "Glycine betaine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
isologs_quant %>% 
  filter(metabolite == "L-Valine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "L-Valine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
isologs_quant %>% 
  filter(metabolite == "L-Isoleucine") %>% 
  filter(umol_enviro <= 1) %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "L-Isoleucine") %>% 
  filter(umol_enviro <= 1) %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
isologs_quant %>% 
  filter(metabolite == "Homarine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "Homarine") %>% 
  filter(umol_enviro <= 0.1) %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
isologs_quant %>% 
  filter(metabolite == "L-Methionine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "L-Methionine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment), position = "stack") + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
isologs_quant %>% 
  filter(metabolite == "Guanine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "Guanine") %>% 
  group_by(treatment, date, metabolite) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
isologs_quant %>% 
  filter(metabolite == "L-Histidine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = nmol, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "L-Histidine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  mutate(nmol = avg_umol_enviro*1000) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = nmol, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
isologs_quant %>% 
  filter(metabolite == "L-Arginine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = avg_umol_enviro, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "L-Arginine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = avg_umol_enviro, fill = treatment)) + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```


```{r}
isologs_quant %>% 
  filter(metabolite == "Arsenobetaine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = avg_umol_enviro, color = treatment)) + 
  scale_color_manual(values = colors) + 
  theme_bw()

isologs_quant %>% 
  filter(metabolite == "Arsenobetaine") %>% 
  group_by(treatment, date) %>% 
  mutate(avg_umol_enviro = mean(umol_enviro)) %>% 
  distinct(avg_umol_enviro, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = avg_umol_enviro, fill = treatment), position = "fill") + 
  scale_fill_manual(values = colors) + 
  theme_bw()
```

```{r}
targout$points %>%
  as.data.frame() %>%
  rownames_to_column("filename") %>%
  left_join(targ_met) %>%
  mutate(col_id=case_when(
    treatment=="C"~"plum2",
    treatment=="ZL"~"darkslategray2",
    treatment=="ZH"~"lightseagreen",
    treatment=="LL"~"gold",
    treatment=="LH"~"lightcoral",
    treatment=="RL"~"orange",
    treatment=="RH"~"brown3",
    treatment=="ZF"~"mediumpurple3", 
    TRUE~"grey50"
  )) %>%
  ggplot() +
  geom_point(aes(x=MDS1, y=MDS2, color=col_id, label = filename, shape = timepoint), size=4) +
  scale_color_identity(name = "treatment", guide = "legend", labels = c("Redfield Ratio N:P, High N:P", "No N + Low P",
                                                                        "Low N:P, Low Dose", "T0 - No Added Nutrients",
                                                                        "Low N:P, High Dose", "No N + High P", "No N + High P + No Fe",
                                                                        "Redfield Ratio N:P, Low N:P", "Control")) +
  scale_shape_discrete(breaks = c("27June", "30June", "14July", "21July", "27July")) +
  theme_bw() + 
  ggtitle("NMDS Plot of Targeted Data")
```
This NMDS plot was averaged by replicate and area was normalized by total POC and vol L filt
 last day - taxonomic change
 LH - physiological change

```{r}
messout$points %>%
  as.data.frame() %>%
  rownames_to_column("filename") %>%
  left_join(mess_data) %>%
  mutate(col_id=case_when(
    treatment=="C"~"plum2",
    treatment=="ZL"~"darkslategray2",
    treatment=="ZH"~"lightseagreen",
    treatment=="LL"~"gold",
    treatment=="LH"~"lightcoral",
    treatment=="RL"~"orange",
    treatment=="RH"~"brown3",
    treatment=="ZF"~"mediumpurple3", 
    TRUE~"grey50"
  )) %>%
  ggplot() +
  geom_point(aes(x=MDS1, y=MDS2, color=col_id, label = filename, shape = timepoint), size=4) +
  scale_color_identity(name = "treatment", guide = "legend", labels = c("Redfield Ratio - High N:P", "No N + Low P", 
                                                                        "Low N:P, Low Dose", "T0 - No Added Nutrients", 
                                                                        "Low N:P, High Dose", "No N + High P", "High P, No Fe", 
                                                                        "Redfield Ratio - Low N:P", "Control")) +
  scale_shape_discrete(breaks = c("27June", "30June", "14July", "21July", "27July")) +
  theme_bw() + 
  ggtitle("NMDS Plot of Selected Good Peaks")
```

```{r}
nb.cols <- 13
mycolors <- colorRampPalette(brewer.pal(8, "Set1"))(nb.cols)
```


```{r}
isologs_quant %>% 
  na.omit() %>% 
  group_by(metabolite, treatment, date) %>% 
  mutate(umol_avg = mean(umol_enviro)) %>% 
  distinct(umol_avg, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = treatment, y = umol_avg, fill = metabolite), position = "fill") +
  facet_wrap(~date) + 
  theme_bw() + 
  scale_fill_manual(values = mycolors)
```

```{r}
isologs_quant %>% 
  na.omit() %>% 
  group_by(metabolite, treatment, date) %>% 
  mutate(umol_avg = mean(umol_enviro)) %>% 
  distinct(umol_avg, .keep_all = TRUE) %>% 
  ggplot() + 
  geom_col(aes(x = date, y = umol_avg, fill = metabolite), position = "fill") +
  facet_wrap(~treatment, ncol = 4) + 
  theme_bw() + 
  scale_fill_manual(values = mycolors)
```

```{r}
ucyna <- read_csv("ucyna.csv") %>% 
  rename(Replicate = Replicate.Name) %>% 
  rename(Metabolite = Precursor.Ion.Name) %>% 
  rename(nmol_in_Culture = nmol.in.Enviro.ave) %>% 
  rename(nmol_Carbon = nmol.C.ave) %>% 
  rename(nmol_Nitrogen = nmol.N.ave) %>% 
  filter(str_detect(Replicate, "Smp_UCYNA")) %>% 
  mutate(Replicate = str_remove(Replicate, "220815_")) 

write.csv(ucyna, file = "UCYNA_Culture_Metabolite_Data.csv", row.names = FALSE)

ucyna <- read_csv("UCYNA_Culture_Metabolite_Data.csv")
```


