---
title: "peridice_chromatograms"
author: "Iris Kern"
date: "2023-09-27"
output: html_document
---

```{r}
library(tidyverse)
library(RaMS)
library(xcms)
```


```{r}
fls <- list.files('HILICpos/', full.names = TRUE)
fls <- as.data.frame(fls)

metadataframe <- fls %>%
  # Grab just the unique filenames and rename the column
  distinct(filename=`fls`) %>%
  mutate(filename = str_remove(filename, "targeted_data/pos/")) %>% 
  # Create a new column with sample type information
  mutate(samp_type=str_extract(filename, "Blk|Smp|Std|Poo")) %>%
  # Create a new column with timepoint information (either Tfinal or T0)
  mutate(timepoint=str_extract(filename, "27June|30June|14July|21July|27July")) %>%
  # Extract treatment information from the filename
  # Longest one needs to go first!
  mutate(treatment=str_extract(filename, "Std|Poo|Blk|C|ZF|ZL|ZH|RL|RH|LL|LH|Tote")) %>%
  # Replace accidental "P" treaments from "Pooled" with NAs
  mutate(treatment=ifelse(samp_type=="Poo", NA, treatment))

msnexp_filled <- readRDS('xcms_output/msnexp_filled2.rds')
```

```{r}
msdata <- msnexp_filled %>%
  fileNames() %>%
  str_subset("Smp") %>%
  str_replace(r"(C:\\Users\\dhruv\\Desktop\\iris\\iris\\HILICpos\\)", "/Users/iriskern/Desktop/work/peridice/HILICpos/") %>%
  grabMSdata(verbosity = 0)
```

```{r}
peak_data_long <- msnexp_filled %>%
  chromPeaks() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  mutate(peakidx=row_number())

peak_data <- msnexp_filled %>%
  featureDefinitions() %>%
  as.data.frame() %>%
  select(mzmed, rtmed, npeaks, peakidx) %>%
  rownames_to_column("id") %>%
  unnest_longer(peakidx) %>%
  rename_with(~paste0("feat_", .x), .cols = -peakidx) %>%
  left_join(peak_data_long) %>%
  mutate(filename=basename(fileNames(msnexp_filled))[sample]) %>% 
  left_join(metadataframe %>% mutate(filename=basename(filename))) %>%
  filter(samp_type=="Smp")
```
