---
title: "PCR"
author: "Iris Kern"
date: "2023-11-28"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(pls)
library(stats)

set.seed(20)
```

```{r}
peridice <- read_csv("PERIDICE_metabolite_data.csv")
gradients <- read_csv("csvs/G1_Metab_Data.csv")
grad_meta <- read_csv("csvs/G1_MetaData.csv")

grad_pcr <- gradients %>% 
  select(-c("Compound_name_in_figures")) %>% 
  pivot_longer(!Complete_compound_name, names_to = "Sample_ID", values_to = "nmol") %>% 
  left_join(grad_meta) %>% 
  rename(metabolite = Complete_compound_name, n_nmol = NO3_NO2, pc = PC_nM, pn = PN_nM) %>% 
  mutate(nm_per_pc = nmol/pc) %>% 
  mutate(n_per_pc = n_nmol/pc) 

# %>%
#   filter(str_detect(metabolite, "Guanine|Arsenobetaine"))

peridice_pcr <- peridice %>% 
  select(nmol, filename, metabolite, n_nmol = added_N_uM, pc, pn) %>% 
  mutate(nm_per_pc = nmol/pc) %>% 
  mutate(n_nmol = replace_na(n_nmol, 0)) %>%
  # filter(str_detect(filename, "T0|27July")) %>% 
  mutate(n_per_pc = n_nmol/pc) %>% 
  # select(nmol, n_nmol) %>% 
  group_by(metabolite, filename) %>%
  # filter(str_detect(metabolite, "Guanine|Arsenobetaine")) %>% 
  mutate(timepoint = str_extract(filename, "27June|30June|14July|21July|27July")) %>% 
  mutate(timepoint = str_replace_all(timepoint, "July", "-7-22")) %>% 
  mutate(timepoint = str_replace_all(timepoint, "June", "-6-22")) %>% 
  mutate(date = as.Date(timepoint, format = "%d-%m-%y")) %>% 
  mutate(treatment = str_extract(filename, "RH|RL|LH|LL|ZH|ZL|ZF|C"))
```

```{r}
peri_pca <- peridice_pcr %>% 
  select(metabolite, filename, nmol) %>% 
  filter(!str_detect(filename, "T0")) %>% 
  distinct(nmol, .keep_all = TRUE) %>% 
  group_by(metabolite) %>% 
  mutate(nmol = rank(nmol)) %>% 
  pivot_wider(names_from = "metabolite", values_from = "nmol") %>% 
  column_to_rownames("filename") %>% 
  data.matrix() %>% 
  `[<-`(is.na(.), 0) %>% 
  prcomp(center = TRUE, scale. = TRUE)

plot(peri_pca)
```


# Gradients Heatmap
```{r}
grad_nmds_heat <- grad_pcr %>% 
  group_by(metabolite, Sample_ID, Time_UTC) %>%
  summarise(avg_nmol = mean(nmol)) %>%
  ungroup() %>%
  mutate(id = paste(Time_UTC, Sample_ID))

# %>% 
#   filter(str_detect(metabolite, "Guanine|Arsenobetaine|Hydroxyisoleucine|Betonicine|Trigonelline|Gonyol|beta-Alanine|Glycine betaine|Carnitine|Sarcosine|L-Cystathionine|Ectoine|Proline betaine|L-Proline|Cytosine|Isethionic acid"))


grad_heatmap_data <- grad_nmds_heat %>% 
  complete(metabolite, id, fill = list(avg_nmol = 0)) %>% 
  group_by(metabolite) %>% 
  # mutate(norm_conc = rank(avg_nmol)) %>%
  mutate(norm_conc = (avg_nmol - min(avg_nmol)) / (max(avg_nmol) - min(avg_nmol))) %>% 
  select(metabolite, norm_conc, id) %>%
  pivot_wider(names_from = "metabolite", values_from = "norm_conc") %>%
  mutate(id=factor(id)) %>%
  arrange(id) %>%
  na.omit() %>% 
  column_to_rownames("id")


grad_plotheatmap <- grad_heatmap_data %>%
  data.matrix() %>% 
  heatmaply(fontsize_row = 5, fontsize_col = 3)
# 
# %>%
#   heatmaply(Rowv = FALSE, fontsize_row = 10, fontsize_col = 7)

# make clustered heatmap from scratch using pheatmap

grad_plotheatmap
```

# Peridice test and train
```{r}
peri_pcr_model <- pcr(n_nmol~date+treatment+nmol, data = peridice_pcr, scale = TRUE, validation = "CV")

test_peri <- predict(peri_pcr_model, newdata = peridice_pcr)

summary(test_peri)
summary(peri_pcr_model)

actual_values <- peridice_pcr$n_nmol

results <- data.frame(actual = actual_values, predicted = test_peri)


summary(pcr_model)
ggplot(results, aes(x = actual, y = predicted.n_nmol.1.comps)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  labs(title = "PERI-DICE train and test",
       x = "Measured N (uM)",
       y = "Predicted N (uM)") +
  # xlim(0,5) + 
  # ylim(0,5) + 
  theme_bw()
```


# testing on gradients, model on gradients
```{r}
grad_pcr_model <- pcr(n_nmol~nm_per_pc+metabolite, data = grad_pcr, scale = TRUE, validation = "LOO")

test_grad <- predict(grad_pcr_model, newdata = grad_pcr)

actual_values <- grad_pcr$n_nmol

results <- data.frame(actual = actual_values, predicted = test_grad) %>% 
  # rename(predicted1 = predicted.n_nmol.1.comps) %>% 
  # filter(predicted1 > 0) %>% 
  na.omit() 
summary(test_grad)

summary(grad_pcr_model)
ggplot(results, aes(x = actual, y = predicted1)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  labs(title = "Gradients 1 Train and Test",
       x = "Measured N (uM)",
       y = "Predicted N (uM)") +
  xlim(0,6) + 
  ylim(0,6) + 
  theme_bw()
```


# testing on peridice, training on gradients
```{r}
grad_pcr_model <- pcr(n_nmol~nm_per_pc+metabolite, data = grad_pcr, scale = TRUE, validation = "LOO")

test_peri <- predict(grad_pcr_model, newdata = peridice_pcr)

summary(test_peri)

actual_values <- peridice_pcr$n_nmol

results <- data.frame(actual = actual_values, predicted = test_peri) %>% 
  rename(predicted1 = predicted.n_nmol.1.comps) %>% 
  rename(predicted2 = predicted.n_nmol.2.comps) %>% 
  na.omit() %>% 
  filter(predicted1 > 0) %>% 
  mutate(error_sq = (predicted1 - actual)^2)


summary(grad_pcr_model)
ggplot(results, aes(x = actual, y = predicted1)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  labs(title = "Gradients 1 Training, PERI-DICE Testing",
       x = "Measured N (uM)",
       y = "Predicted N (uM)") +
  theme_bw() + 
  xlim(0, 5) + 
  ylim(0, 5)
```


## testing on gradients, training on peridice
```{r}
pcr_model <- pcr(n_nmol~nm_per_pc+metabolite, data = peridice_pcr, scale = TRUE, validation = "LOO")

test_grad <- predict(pcr_model, newdata = grad_pcr)

actual_values <- grad_pcr$n_nmol

results <- data.frame(actual = actual_values, predicted = test_grad) %>% 
  rename(predicted1 = predicted.n_nmol.1.comps)

mean((test_grad - actual_values)^2)

summary(pcr_model)
ggplot(results, aes(x = actual, y = predicted1)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  labs(title = "PERI-DICE Training, Gradients 1 Testing",
       x = "Measured N (uM)",
       y = "Predicted N (uM)") +
  theme_bw() + 
  xlim(0,5) + 
  ylim(0,5)
```

gradients 1 principal component 


```{r}
peridice_pcr %>% 
  filter(metabolite == "Cytosine") %>% 
  ggplot() + 
  geom_point(aes(x = nmol, y = pc, color = factor(date)))

peri_pcr_model <- pcr(pc~date+treatment+nmol, data = peridice_pcr, scale = TRUE, centers = TRUE, validation = "LOO")

test_peri <- predict(peri_pcr_model, newdata = peridice_pcr)

summary(test_peri)
summary(peri_pcr_model) 

actual_values <- peridice_pcr$pc

results <- data.frame(actual = actual_values, predicted = test_peri)

ggplot(results, aes(x = actual, y = predicted.pc.9.comps)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  xlim(0,30) +
  ylim(0,30) +
  xlab("Measured Particulate Carbon") + 
  ylab("Predicted Particulate Carbon") + 
  theme_bw()
```

```{r}
grad_pcr_model <- pcr(pc~Binned_latitude+nmol+Sample_ID, data = grad_pcr, scale = TRUE, centers = TRUE, validation = "CV")

test_grad <- predict(grad_pcr_model, newdata = grad_pcr)

summary(test_grad)
summary(grad_pcr_model)

grad_actual_values <- grad_pcr$pc

grad_results <- data.frame(actual = grad_actual_values, predicted = test_grad)

ggplot(grad_results, aes(x = actual, y = predicted.pc.1.comps)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  # xlim(0,5) + 
  # ylim(0,5) + 
  theme_bw()
```

