---
title: "PERI-DICE Preliminary Figures"
author: "Iris Kern"
date: "2023-10-06"
output: html_document
---
```{r setup, warnings = FALSE, echo = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(plotly)
library(vegan)
library(heatmaply)
library(ggnewscale)
library(readr)

set.seed(20)

```



```{r, warnings = FALSE, echo = FALSE, message = FALSE}
quant_data <- read_csv("csvs/quant_data.csv")
metadataframe <- read_csv("csvs/metadataframe.csv")
```


```{r, warnings = FALSE, echo = FALSE, message = FALSE}
data_vis <- quant_data %>%  
  mutate(treatment = str_extract(replicate, "Std|Poo|Blk|C|ZF|ZL|ZH|RL|RH|LL|LH|Tote")) %>% 
  mutate(timepoint = str_extract(replicate, "27June|30June|14July|21July|27July")) %>% 
  mutate(timepoint = str_replace_all(timepoint, "July", "-7-22")) %>% 
  mutate(timepoint = str_replace_all(timepoint, "June", "-6-22")) %>% 
  mutate(date = as.Date(timepoint, format = "%d-%m-%y")) %>% 
  select(metabolite, treatment, date, nM, replicate) %>% 
  filter(metabolite != "Sodium 2-mercaptoethanesulfonate") %>% 
  filter(metabolite != "Fumaric acid") %>% 
  na.omit()

level_order <- c("Tote", "C", "ZF", "ZL", "ZH", "LL", "LH", "RL", "RH")

heat_level_order_treat <- c("2022-06-27 Tote", "2022-06-30 C",  "2022-07-14 C",  "2022-07-21 C",  "2022-07-27 C",  
                            "2022-06-30 ZF", "2022-07-14 ZF", "2022-07-21 ZF", "2022-07-27 ZF",
                            "2022-06-30 ZL", "2022-07-14 ZL", "2022-07-21 ZL", "2022-07-27 ZL", 
                            "2022-06-30 ZH", "2022-07-14 ZH", "2022-07-21 ZH", "2022-07-27 ZH",
                            "2022-06-30 LL", "2022-07-14 LL", "2022-07-21 LL", "2022-07-27 LL",
                            "2022-06-30 LH", "2022-07-14 LH", "2022-07-21 LH", "2022-07-27 LH", 
                            "2022-06-30 RL", "2022-07-14 RL", "2022-07-21 RL", "2022-07-27 RL",
                            "2022-06-30 RH", "2022-07-14 RH", "2022-07-21 RH", "2022-07-27 RH")

heat_level_order_date <- c("2022-06-27 Tote", "2022-06-30 C","2022-06-30 ZF", "2022-06-30 ZL", 
                           "2022-06-30 ZH", "2022-06-30 LL","2022-06-30 LH", "2022-06-30 RL", "2022-06-30 RH",
                           "2022-07-14 C", "2022-07-14 ZF", "2022-07-14 ZL", "2022-07-14 ZH", "2022-07-14 LL", 
                           "2022-07-14 LH", "2022-07-14 RL", "2022-07-14 RH", 
                           "2022-07-21 C", "2022-07-21 ZF", "2022-07-21 ZL", "2022-07-21 ZH", 
                           "2022-07-21 LL", "2022-07-21 LH", "2022-07-21 RL", "2022-07-21 RH", 
                           "2022-07-27 C", "2022-07-27 ZF", "2022-07-27 ZL",  
                           "2022-07-27 ZH", "2022-07-27 LL", "2022-07-27 LH", "2022-07-27 RL",  "2022-07-27 RH")
```


```{r, warnings = FALSE, echo = FALSE, message = FALSE}
data_vis_fc <- data_vis %>% 
  select(-c("replicate")) %>% 
  filter(!str_detect(treatment, "Tote")) %>% 
  pivot_wider(names_from = treatment, values_from = nM, values_fn = mean) %>% 
  pivot_longer(cols = c(ZF, ZL, ZH, LL, LH, RL, RH)) %>% 
  mutate(fold_change = log2(value/C))

data_vis_km <- data_vis %>% 
  pivot_wider(names_from = metabolite, values_from = nM) %>% 
  select(-c("treatment", "date")) %>% 
  column_to_rownames("replicate") %>% 
  data.matrix() %>%
  `[<-`(is.na(.), 0) %>%
  scale() %>%
  t() %>%
  kmeans(centers = 6) %>% 
  pluck("cluster") %>%
  as.data.frame() %>%
  set_names("cluster") %>%
  rownames_to_column("metabolite")

data_vis_cluster <- data_vis_fc %>% 
  left_join(data_vis_km) %>% 
  rename(control = C, treatment = name, nM = value) %>% 
  mutate(cluster = as.numeric(cluster))
```


```{r, warnings = FALSE, echo = FALSE, message = FALSE}
data_vis_cluster %>% 
  na.omit() %>% 
  group_by(cluster, date, treatment) %>% 
  filter(str_detect(treatment, "RH|RL|LH|LL")) %>% 
  mutate(avg_fc = mean(fold_change)) %>% 
  ggplot(aes(x = date, y = avg_fc, color = factor(treatment, levels = level_order))) + 
  geom_point() +
  geom_line() + 
  theme_bw() + 
  facet_wrap(~cluster) +
  scale_color_manual(values = c("gold", "lightcoral", "orange", "brown3"),
                     labels = c("6N:1P, low dose added", "6N:1P, high dose added",
                                "6N:1P, low dose added", "16N:1P, high dose added"),
                     name = "Treatment") +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("Average Foldchange (From Control) for Each Treatment")
```


```{r, warnings = FALSE, echo = FALSE, message = FALSE}
quant_nmds <- data_vis %>% 
  # arrange(desc(nM)) %>% 
  # group_by(metabolite, replicate) %>% 
  # slice(1) %>% 
  group_by(metabolite, treatment, date) %>%
  summarise(avg_nmol = mean(nM)) %>%
  ungroup() %>%
  # complete(metabolite, date, treatment) %>%
  # mutate(avg_nmol = replace_na(avg_nmol, 0)) %>%
  mutate(id = paste(date, treatment)) %>% 
  filter(!str_detect(id, "Tote|ZL|ZH|ZF"))

quant_mat <- quant_nmds %>%
  group_by(metabolite) %>%
  mutate(norm_conc = rank(avg_nmol)) %>%
  select(metabolite, norm_conc, id) %>% 
  pivot_wider(names_from = "metabolite", values_from = "norm_conc", values_fill = 0) %>%
  column_to_rownames("id") %>%
  data.matrix() 

mdsout <- quant_mat %>%
  metaMDS(k = 2, autotransform = FALSE)

mds_data <- metadataframe %>% 
  ungroup() %>% 
  mutate(timepoint = str_replace_all(timepoint, "July", "-7-22")) %>% 
  mutate(timepoint = str_replace_all(timepoint, "June", "-6-22")) %>% 
  mutate(date = as.Date(timepoint, format = "%d-%m-%y")) %>% 
  filter(str_detect(filename, "Smp")) %>% 
  mutate(treatment = str_remove(treatment, "\\d")) %>% 
  mutate(id = paste(date, treatment))

# %>% 
#   select(-c("replicate", "filename"))

mdsout$points %>%
  as.data.frame() %>%
  rownames_to_column("id") %>%
  left_join(mds_data) %>%
  mutate(date_fct = factor(date)) %>% 
  ggplot() +
  geom_point(aes(x=MDS1, y=MDS2, color=treatment, shape = date_fct), size=4) +
  scale_color_manual(values = c("plum2", "gold", "lightcoral", "orange", "brown3"), 
                     labels = c("Control - no nutrients added", "6N:1P, low dose added", 
                                "6N:1P, high dose added", 
                                "16N:1P, low dose added", "16N:1P, high dose added"),
                     name = "Treatment") +
  scale_shape_discrete(name = "Date") + 
  theme_bw() + 
  ggtitle("Variation of Metabolite Concentration (nM) Across Treatments")
```


```{r, warnings = FALSE, echo = FALSE, message = FALSE}
aminos <- read.csv(
  "https://raw.githubusercontent.com/IngallsLabUW/Ingalls_Standards/master/Ingalls_Lab_Standards.csv",
                              stringsAsFactors = FALSE, header = TRUE) %>% 
  filter(Compound_Type == "Amino Acid") %>% 
  select(metabolite = Compound_Name, emp_form = Empirical_Formula, metabolite_name = Compound_Name_Figure)

peridice_aas <- data_vis %>% 
  filter(metabolite %in% aminos$metabolite)

peridice_aas %>% 
  group_by(metabolite, treatment, date) %>% 
  filter(str_detect(treatment, "C|RH|RL|LH|LL")) %>% 
  ggplot(aes(x = factor(date), y = nM, color = factor(treatment, levels = level_order))) +
  geom_boxplot() + 
  scale_color_manual(values = c("plum2", "gold", "lightcoral", "orange", "brown3"),
                     labels = c("Control", "6N:1P, low dose added",
                                "6N:1P, high dose added",
                                "16N:1P, low dose added", "16N:1P, high dose added"),
                     name = "Treatment") +
  guides(fill=guide_legend(ncol=2)) + 
  theme_bw() + 
  xlab("Date") + 
  ylab("nM (nmol per L)") + 
  facet_wrap(~metabolite, scales = "free_y") + 
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("Amino Acid Concentrations Across Treatments")
```


```{r, warning = FALSE, echo = FALSE, message = FALSE}
osmos <- read.csv(
  "https://raw.githubusercontent.com/IngallsLabUW/Ingalls_Standards/master/Ingalls_Lab_Standards.csv",
                              stringsAsFactors = FALSE, header = TRUE) %>% 
  filter(Compound_Type == "Osmolyte") %>% 
  select(metabolite = Compound_Name, emp_form = Empirical_Formula, metabolite_name = Compound_Name_Figure)

peridice_osmos <- data_vis %>% 
  filter(metabolite %in% osmos$metabolite)

peridice_osmos %>% 
  group_by(metabolite, treatment, date) %>% 
  # filter(!str_detect(treatment, "Tote")) %>% 
  filter(str_detect(treatment, "C|RH|RL|LH|LL")) %>% 
  filter(str_detect(metabolite, "2-O-alpha-D-Glucosylglycerol|Ectoine|Ethanolamine|Trimethylamine N-oxide")) %>% 
  ggplot(aes(x = factor(date), y = nM, color = factor(treatment, levels = level_order))) +
  geom_boxplot() + 
  scale_color_manual(values = c("plum2", "gold", "lightcoral", "orange", "brown3"),
                     labels = c("Control", "6N:1P, low dose added",
                                "6N:1P, high dose added",
                                "16N:1P, low dose added", "16N:1P, high dose added"),
                     name = "Treatment") +
  guides(fill=guide_legend(ncol=2)) + 
  theme_bw() + 
  xlab("Date") + 
  ylab("nM (nmol per L)") + 
  facet_wrap(~metabolite, scales = "free_y") + 
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("Osmolyte Concentrations Across Treatments")
```


```{r, warning = FALSE, echo = FALSE, message = FALSE}
nucleos <- read.csv(
  "https://raw.githubusercontent.com/IngallsLabUW/Ingalls_Standards/master/Ingalls_Lab_Standards.csv",
                              stringsAsFactors = FALSE, header = TRUE) %>% 
  filter(Compound_Type == "Nucleic Acid") %>% 
  select(metabolite = Compound_Name, emp_form = Empirical_Formula, metabolite_name = Compound_Name_Figure)

peridice_nucleos <- data_vis %>% 
  filter(metabolite %in% nucleos$metabolite)

peridice_nucleos %>% 
  group_by(metabolite, treatment, date) %>% 
  # filter(!str_detect(treatment, "Tote")) %>% 
  filter(str_detect(treatment, "C|RH|RL|LH|LL")) %>% 
  ggplot(aes(x = factor(date), y = nM, color = factor(treatment, levels = level_order))) +
  geom_boxplot() + 
  scale_color_manual(values = c("plum2", "gold", "lightcoral", "orange", "brown3"),
                     labels = c("Control", "6N:1P, low dose added",
                                "6N:1P, high dose added",
                                "16N:1P, low dose added", "16N:1P, high dose added"),
                     name = "Treatment") +
  guides(fill=guide_legend(ncol=2)) + 
  theme_bw() + 
  xlab("Date") + 
  ylab("nM (nmol per L)") + 
  facet_wrap(~metabolite, scales = "free_y") + 
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("Nucleic Acid Concentrations Across Treatments")
```

```{r, warning = FALSE, echo = FALSE, message = FALSE}
sulfur <- read.csv(
  "https://raw.githubusercontent.com/IngallsLabUW/Ingalls_Standards/master/Ingalls_Lab_Standards.csv",
                              stringsAsFactors = FALSE, header = TRUE) %>% 
  filter(Compound_Type == "Sulfur") %>% 
  select(metabolite = Compound_Name, emp_form = Empirical_Formula, metabolite_name = Compound_Name_Figure)

peridice_sulf <- data_vis %>% 
  filter(metabolite %in% sulfur$metabolite) %>% 
  filter(metabolite != "2-Hydroxy-4-(methylthio)butyric acid") %>% 
  filter(metabolite != "L-Cysteinesulfinic acid") %>% 
  filter(metabolite != "Sodium taurocholate") %>% 
  filter(metabolite != "Amino hydroxypropanesulfonate") %>% 
  filter(metabolite != "3-Aminopropanesulfonate") %>% 
  filter(metabolite != "3-Sulfopyruvic acid") %>% 
  filter(metabolite != "2-keto-4-methylthiobutyric acid")

peridice_sulf %>% 
  group_by(metabolite, treatment, date) %>% 
  # filter(!str_detect(treatment, "Tote")) %>% 
  filter(str_detect(treatment, "C|RH|RL|LH|LL")) %>% 
  ggplot(aes(x = factor(date), y = nM, color = factor(treatment, levels = level_order))) +
  geom_boxplot() + 
  scale_color_manual(values = c("plum2", "gold", "lightcoral", "orange", "brown3"),
                     labels = c("Control", "6N:1P, low dose added",
                                "6N:1P, high dose added",
                                "16N:1P, low dose added", "16N:1P, high dose added"),
                     name = "Treatment") +
  guides(fill=guide_legend(ncol=2)) + 
  theme_bw() + 
  xlab("Date") + 
  ylab("nM (nmol per L)") + 
  facet_wrap(~metabolite, scales = "free_y") + 
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("Sulfur-Containing Compounds Concentrations Across Treatments")
```

